# -*- coding: utf-8 -*-
"""my practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1erXAOoxT5yNfdMRKot4EccjfvD1e0iV4
"""



"""Create a 1D array of numbers from 0 to 9"""

import numpy

arr = numpy.array([0,1,2,3,4,5,6,7,8,9])

print(arr)

"""Create a 2D array with shape (3, 3), where values range from 1 to 9.

"""

import numpy as np

arr2 = np.array([[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])

print(arr2)

"""Create a 3D array of shape (2, 3, 4) filled with random integers from 1 to 100."""

import numpy as np

arr3 = np.array([[[1, 2,0], [2,1,0], [4,3,0]],
 [[1,2,3], [4,3,2], [3,3,3]],
 [[4,3,2], [1,2,3], [4,4,4]]])

print(arr3)

"""Given the array arr2 from Task 1, extract the second row.

"""

second_row = arr2[1]
print(second_row)

"""Extract the element at the 3rd row and 2nd column of arr2."""

element = arr2[2, 1]
print(element)

"""Extract all elements from the 3D array arr3 at the first index (0th layer)"""

firstIndex=arr3[0]
print(firstIndex)

"""Reshape the 1D array from Task 1 into a 2x5 2D array"""

# prompt: Reshape the 1D array from Task 1 into a 2x5 2D array

reshaped_arr = arr(2, 5)
print(reshaped_arr)